CREATE TABLE [dbo].[Logs]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Level] VARCHAR(25) NULL, 
    [Message] VARCHAR(MAX) NULL, 
    [TimeStamp] DATETIME NOT NULL DEFAULT GETDATE(), 
    [Exception] VARCHAR(MAX) NULL
)
