CREATE TABLE [dbo].[Players]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [UserName] VARCHAR(50) NOT NULL, 
    [LastActivity] DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET(), 
    [Admin] BIT NOT NULL DEFAULT 0, 
    [Wins] INT NOT NULL DEFAULT 0 
)
